from fastapi import APIRouter, HTTPException
from pydantic import BaseModel, Field
from services.retrieval_service import retrieve_context, generate_answer_with_llm

router = APIRouter()

from typing import Literal

class QuestionRequest(BaseModel):
    question: str = Field(..., description="The question to ask the RAG system.")
    n_results: int = Field(2, ge=1, le=10, description="The number of matching text chunks to retrieve.")
    mode: Literal["strict", "hybrid"] = Field("strict", description="Use 'strict' to only answer from context, or 'hybrid' to allow general AI knowledge.")

class QuestionResponse(BaseModel):
    answer: str
    confidence_score: int
    context: list[str]

@router.post("/ask", response_model=QuestionResponse)
def ask_question(request: QuestionRequest):
    """
    Endpoint to ask a question. Finds relevant context in ChromaDB and returns an answer generated by the LLM.
    """
    if not request.question.strip():
        raise HTTPException(status_code=400, detail="Question text cannot be empty.")

    try:
        context_str, context_list, retrieval_confidence = retrieve_context(request.question, n_results=request.n_results)
        ai_result = generate_answer_with_llm(request.question, context_str, mode=request.mode)
        
        return QuestionResponse(
            answer=ai_result["answer"],
            confidence_score=retrieval_confidence,
            context=context_list
        )
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))
