from fastapi import APIRouter, HTTPException
from pydantic import BaseModel, Field
from services.retrieval_service import retrieve_context, generate_answer_with_llm

router = APIRouter()

class QuestionRequest(BaseModel):
    question: str = Field(..., description="The question to ask the RAG system.")
    n_results: int = Field(3, ge=1, le=10, description="The number of matching text chunks to retrieve.")

class QuestionResponse(BaseModel):
    answer: str
    context: list[str]

@router.post("/ask", response_model=QuestionResponse)
def ask_question(request: QuestionRequest):
    """
    Endpoint to ask a question. Finds relevant context in ChromaDB and returns an answer generated by the LLM.
    """
    if not request.question.strip():
        raise HTTPException(status_code=400, detail="Question text cannot be empty.")

    try:
        context_str, context_list = retrieve_context(request.question, n_results=request.n_results)
        answer = generate_answer_with_llm(request.question, context_str)
        
        return QuestionResponse(
            answer=answer,
            context=context_list
        )
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))
